---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: servicemesh-operator
  namespace: openshift-operators 
spec:
  config:
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        value: reserved
      - effect: NoExecute
        key: node-role.kubernetes.io/infra
        value: reserved
  channel: stable
  installPlanApproval: Automatic
  name: servicemeshoperator
  source: redhat-operators-index
  sourceNamespace: openshift-marketplace
...
