---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: ${INFRASTRUCTURE_ID}
  name: ${INFRASTRUCTURE_ID}-gpu-worker-eu-west-1a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ${INFRASTRUCTURE_ID}
      machine.openshift.io/cluster-api-machineset: ${INFRASTRUCTURE_ID}-gpu-worker-eu-west-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ${INFRASTRUCTURE_ID}
        machine.openshift.io/cluster-api-machine-role: worker 
        machine.openshift.io/cluster-api-machine-type: worker 
        machine.openshift.io/cluster-api-machineset: ${INFRASTRUCTURE_ID}-gpu-worker-eu-west-1a
        usage: virtualization
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
          node-role.kubernetes.io/gpu-worker: ""
      providerSpec:
        value:
          ami:
            id: ${AMI}
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: ${INFRASTRUCTURE_ID}-worker-profile
          # Amazon EC2 G4dn instances are designed to help accelerate machine learning inference and graphics-intensive workloads.
          instanceType: g4dn.4xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: eu-west-1a
            region: eu-west-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - ${INFRASTRUCTURE_ID}-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - ${INFRASTRUCTURE_ID}-private-eu-west-1a
          tags:
            - name: kubernetes.io/cluster/${INFRASTRUCTURE_ID}
              value: owned
          userDataSecret:
            name: worker-user-data
